replicaCount: 5

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: cert-manager-test.projectxconsulting.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: artemis-tls
      hosts:
        - cert-manager-test.projectxconsulting.net
